INSERT INTO Planet (NAME, ROTATION_PERIOD, DIAMETER, WEATHER, LAND, COUNTER)
VALUES ('Mercury', 1416, 9760, 'Hottest', 'Rocky', 0);

INSERT INTO Planet (NAME, ROTATION_PERIOD, DIAMETER, WEATHER, LAND, COUNTER)
VALUES ('Venus', 5832, 12102, 'Hot', 'Thick, yellow clouds', 0);

INSERT INTO Planet (NAME, ROTATION_PERIOD, DIAMETER, WEATHER, LAND, COUNTER)
VALUES ('Earth', 24, 12742, 'Perfect', 'Liquid water on the surface', 0);

INSERT INTO Planet (NAME, ROTATION_PERIOD, DIAMETER, WEATHER, LAND, COUNTER)
VALUES ('Mars', 24, 6778, 'Cold', 'Desert', 0);

INSERT INTO Planet (NAME, ROTATION_PERIOD, DIAMETER, WEATHER, LAND, COUNTER)
VALUES ('Jupiter', 10, 139822, 'Cold', 'Windy clouds and water', 0);

INSERT INTO Planet (NAME, ROTATION_PERIOD, DIAMETER, WEATHER, LAND, COUNTER)
VALUES ('Saturn', 11, 116464, 'Cold', 'Made of chunks of ice and rock', 0);

INSERT INTO Planet (NAME, ROTATION_PERIOD, DIAMETER, WEATHER, LAND, COUNTER)
VALUES ('Uranus', 17, 50724, 'Cold', 'Ice', 0);

INSERT INTO Planet (NAME, ROTATION_PERIOD, DIAMETER, WEATHER, LAND, COUNTER)
VALUES ('Neptune', 16, 49244, 'Cold', 'Ice', 0);

